ServerEvents.recipes(event => {
    const GT = event.recipes.gtceu;
    event.remove({ input: 'minecraft:sugar_cane', output: 'minecraft:sugar' });   // さとうきびルート   (改変)
    event.remove({ input: 'minecraft:beetroot', output: 'minecraft:sugar' });     // ビートルートルート (改変)
    event.remove({ input: 'minecraft:honey_bottle', output: 'minecraft:sugar' }); // はちみつルート     (封印)
    event.remove({ input: 'pamhc2crops:agaveitem', output: 'minecraft:sugar' });  // サイザル麻ルート   (封印)
    // 4x さとうきび → 1x さとうきびの粉 (LV)
    GT.macerator('replace_sugarcane_macerating')
        .itemInputs('4x minecraft:sugar_cane')
        .itemOutputs('kubejs:sugarcane_dust')
        .duration(1600)
        .EUt(GTValues.VA[GTValues.LV]);
    // さとうきびの粉 → さとうきびのエキス 250mB (EV)
    GT.extractor('sugarcane_juice')
        .itemInputs('kubejs:sugarcane_dust')
        .outputFluids('kubejs:sugarcane_juice 250')
        .duration(800)
        .EUt(GTValues.VA[GTValues.EV]);
    // さとうきびのエキス 2000mB → 水 1750mB + 黒糖 (EV)
    GT.distillation_tower('muscovado')
        .inputFluids('kubejs:sugarcane_juice 1000')
        .itemOutputs('kubejs:muscovado')
        .outputFluids('minecraft:water 1750')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV]);
    // 2x 黒糖 → モラセス 1500mB + 粗糖 (50％) (EV)
    GT.centrifuge('raw_sugar')
        .itemInputs('2x kubejs:muscovado')
        .chancedOutput('kubejs:raw_sugar', 5000, 0)
        .outputFluids('kubejs:molasses 1500')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV]);
    // モラセス 1000mB → 粗糖 + 糖蜜 500mB (EV)
    GT.centrifuge('molasses_processing')
        .inputFluids('kubejs:molasses 500')
        .itemOutputs('kubejs:raw_sugar')
        .outputFluids('kubejs:sugar_syrup 500')
        .duration(1200)
        .EUt(GTValues.VA[GTValues.EV]);
    // 4x 粗糖 + 蒸留水 1500mB → ローリカー 1000mB (LV)
    GT.brewery('raw_sugar_solution')
        .itemInputs('4x kubejs:raw_sugar')
        .inputFluids('kubejs:sugar_syrup 1500')
        .outputFluids('kubejs:raw_sugar_solution')
        .duration(2400)
        .EUt(GTValues.VA[GTValues.LV]);
    // ローリカー 1000mB + 二酸化炭素 500mB + 2x 水酸化カルシウム → ブラウンリカー 2000mB + 2x バイオチャフ (MV)
    GT.mixer('washed_sugar_solution')
        .itemInputs('2x #forge:dusts/calcium_hydroxide')
        .inputFluids('#forge:carbon_dioxide 500', 'kubejs:raw_sugar_solution 1000')
        .itemOutputs('2x gtceu:bio_chaff')
        .outputFluids('kubejs:washed_sugar_solution 2000')
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV]);
    // ブラウンリカー 1000mB + 4x 活性炭 → ファインリカー 1000mB + バイオチャフ (MV)
    GT.mixer('purified_sugar_solution')
        .itemInputs('4x gtceu:activated_carbon_dust')
        .inputFluids('kubejs:washed_sugar_solution 1000')
        .itemOutputs('gtceu:bio_chaff')
        .outputFluids('kubejs:purified_sugar_solution')
        .duration(1200)
        .EUt(GTValues.VA[GTValues.MV]);
    // ファインリカー 1000mB → 水 500mB + 白下 500mB (MV)
    GT.distillation_tower('shiroshita_sugar')
        .inputFluids('kubejs:purified_sugar_solution')
        .outputFluids('minecraft:water 500', 'kubejs:shiroshita_sugar 500')
        .duration(1200)
        .EUt(GTValues.VA[GTValues.MV]);
    // 白下 100mB → 砂糖 x(2 (100％) / 2 (50％+) / 2 (25％+)) + 水 50mB (EV)
    GT.centrifuge('sugar_deploy')
        .inputFluids('kubejs:shiroshita_sugar 100')
        .itemOutputs('2x minecraft:sugar')
        .chancedOutput('2x minecraft:sugar', 5000, 250)
        .chancedOutput('2x minecraft:sugar', 2500, 500)
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV]);
    // 砂糖 + 粗糖 + 蒸留水 1500mB → ローリカー 1500mB (IV)
    GT.mixer('alternative_raw_sugar_solution_recipes')
        .itemInputs('minecraft:sugar', 'kubejs:raw_sugar')
        .inputFluids('kubejs:sugar_syrup 1500')
        .outputFluids('kubejs:raw_sugar_solution 1500')
        .duration(200)
        .EUt(GTValues.VA[GTValues.IV]);
    // 16x ビートルート + 蒸留水 1000mB → 生のてんさい溶液 2000mB (EV)
    GT.brewery('raw_beetroot_solution')
        .itemInputs('16x minecraft:beetroot')
        .inputFluids('#forge:distilled_water 1000')
        .outputFluids('kubejs:raw_beetroot_solution 2000')
        .duration(1200)
        .EUt(GTValues.VA[GTValues.EV]);
    // 生のてんさい溶液 1000mB → 蒸留したてんさい溶液 500mB + 3x バイオチャフ (EV)
    GT.distillation_tower('distilled_beetroot_solution')
        .inputFluids('kubejs:raw_beetroot_solution 1000')
        .itemOutputs('3x gtceu:bio_chaff')
        .outputFluids('kubejs:distilled_beetroot_solution 500')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV]);
    // 蒸留したてんさい溶液 100mB → 砂糖 x(2 (100％) / 2 (50％) / 2 (25％) / 2 (5％)) + 水 50mB (EV)
    GT.centrifuge('sugar_deploy_from_beetroot')
        .inputFluids('kubejs:distilled_beetroot_solution 100')
        .itemOutputs('2x minecraft:sugar')
        .chancedOutput('2x minecraft:sugar', 5000, 0)
        .chancedOutput('2x minecraft:sugar', 2500, 0)
        .chancedOutput('2x minecraft:sugar',  500, 0)
        .duration(120)
        .EUt(GTValues.VA[GTValues.EV]);
    // 64x 砂糖 + 蒸留水 1000mB → 糖蜜 1000mB (IV)
    GT.large_chemical_reactor('sugar_syrup')
        .itemInputs('64x #forge:dusts/sugar')
        .inputFluids('#forge:distilled_water 1000')
        .outputFluids('kubejs:sugar_syrup')
        .duration(1200)
        .EUt(GTValues.VA[GTValues.IV]);
});
